version: "3.8"

services:
  postgres:
    image: postgres:17.4
    container_name: postgres_lab
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: insurance_company
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d insurance_company"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
