# Generated by Django 5.2.7 on 2025-10-31 10:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=512)),
                ('tax_number', models.CharField(max_length=128, unique=True)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=512, unique=True)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_number', models.CharField(max_length=64, unique=True)),
                ('policy_type', models.CharField(max_length=64)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('premium', models.DecimalField(decimal_places=2, default=75, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='insurance.customer')),
            ],
            options={
                'db_table': 'insurance_policy',
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy')),
            ],
            options={
                'db_table': 'claim',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.claim')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddConstraint(
            model_name='insurancepolicy',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='insurance_policy_end_after_start'),
        ),
    ]
